### ISSUE TITLE
Issue in accessing Strapi 

### ISSUE THREAD

**Issue by ramy-coder** [dev-launchers/dev-launchers-platform#1659]
There is issue in accessing Strapi. The error is based on access. I am using the integration test credentials provided on the Strapi [codebase.]
The screenshot of the error:
(<img width="706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFU3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e87b934b481bc87164f831cf53e124b61024dea/strapi%20error.png" alt="strapi error.png" />
) 

Logs: 
[2023-12-22 18:37:22.967] http: GET /admin/ (30 ms) 200
[2023-12-22 18:37:23.465] http: GET /admin/project-type (19 ms) 200
[2023-12-22 18:37:23.684] http: GET /admin/init (10 ms) 200
[2023-12-22 18:37:23.710] http: GET /admin/telemetry-properties (5 ms) 401
[2023-12-22 18:37:49.479] error: Invalid credentials
ApplicationError: Invalid credentials
    at C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\@strapi\admin\server\controllers\authentication.js:36:17
    at callback (C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\koa-passport\lib\framework\koa.js:93:25)
    at allFailed (C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\passport\lib\middleware\authenticate.js:110:18)
    at attempt (C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\passport\lib\middleware\authenticate.js:183:28)
    at strategy.fail (C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\passport\lib\middleware\authenticate.js:305:9)
    at verified (C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\passport-local\lib\strategy.js:82:30)
    at C:\Users\User\Documents\Ramya\Projects\strapiv4-main\node_modules\@strapi\admin\server\services\passport\local-strategy.js:21:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Associated Figma File - 
https://www.figma.com/file/45UefAfsVbjzqpZrN6bM5X/Dev-Recruit---JOIN-Flow-%5Bupdated-grid-system%5D?type=design&node-id=19-9770&mode=design&t=FsFmM2LpdQLJufKd-0

**Comment by Enjoy2Live** [comment]
@ramy-coder what are the steps you followed for this error happen?

**Comment by Enjoy2Live** [comment]
@ramy-coder I'll wait to hear your experience with running it with docker before investigating it using the regular method.
please keep me updated here, thanks!

**Comment by ramy-coder** [comment]
Sure thanks Mohammed, I will keep you posted.
I will be working on it next week, as there are few other activities which
are currently on.

**Comment by Enjoy2Live** [comment]
Hi @ramy-coder , have you had the chance to run strapi using docker?

**Comment by ramy-coder** [comment]
Issue closed
